library(facets)
filename=paste("../", pt, "_Germ1.facets.sort.txt",sep="")
data=read.table(filename)
colnames(data)=c("Chromosome","Position","NOR.DP","NOR.RD","TUM.DP","TUM.RD")
xx=preProcSample(data, ndepth=15)
oo=procSample(xx, min.nhet=5)
fit2=emcncf2(oo)
print(paste("ploidy of sample",pt))
print(fit2$ploidy)
print(paste("purity of sample",pt))
print(fit2$purity)
rdata_name=paste(pt,"_fit2_facets.RData",sep="")
save(xx, oo, fit2, file=rdata_name)
cncf=fit2$cncf[,c(1,10,11,12,13,14,15,2,3,4,5,6,7,8,9)]
write.table(cncf, paste(pt,"_fit2_cncf.txt",sep=""),row.names=FALSE,col.names=TRUE,quote=FALSE,sep="\t")
pdf_name=paste(pt,"plot.pdf", sep="")
pdf(pdf_name)
plotSample(x=oo, emfit=fit2)
dev.off()
